POST http://localhost:4000/app/signup
Content-Type: application/json

{
    "fullName": "Faraz",
    "email": "faraz@mail.com",
    "mobile": "1234567892",
    "password": "Faraz",
    "confirmPassword": "Faraz"
}